services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: france-stick-fighting-web
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
    command: pnpm dev

volumes:
  node_modules:

